---
- name: install | Installing HashiCorp Consul
  unarchive:
    src: "{{ 'https://releases.hashicorp.com/consul/'+consul_agent_version|string+'/consul_'+consul_agent_version|string+'_linux_amd64.zip' }}"
    dest: "{{ consul_agent_install_dir+'/' }}"
    remote_src: true
  become: true
